### ISSUE TITLE
Too many dynamic allocation.

### ISSUE THREAD

**Issue by npaster** [wareHHOuse/diskpp#63]
We have a lot of dynamic allocation everywhere in the code.

Maybe we can try to remove some allocation to improve the performance of the code

**Comment by datafl4sh** [comment]
Hello @npaster,
Could you please provide some examples? I do agree that Eigen in the background does dynamic allocation and that the HHO operators are not optimal in terms of speed. However, I am not sure to which extent this is causing performance problems (it is actually something I am investigating in this moment).

Using dynamically allocated matrices was a choice I did at the beginning in order to be able to keep the code sufficiently general. Creating fully static operators would mean templating them on the element type and on the degree, and this would have an impact also on the way we compute the quadratures.

If you provide me some hints, we can dig a bit deeper the problem.
